version: '3.8'

services:
  db:
    image: motorway-test-backend
    container_name: motorway-test-backend
    build:
      context: .
      target: motorway-test-backend
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=motorway
    ports:
      - 5432:5432
  db_test:
    image: motorway-test-backend
    container_name: motorway-test-backend_test
    build:
      context: .
      target: motorway-test-backend
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=motorway_test
    ports:
      - 5433:5432
  app:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - '${PORT}:${PORT}'
    environment:
      - PORT=${PORT}
      - DB_HOST=db
      - MEMCACHE_SERVERS=memcached:11211
    env_file:
      - .env
    volumes:
      - .:/usr/src/app

  memcached:
    image: bitnami/memcached
    container_name: memcached
    ports:
      - 11211:11211
