receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  otlphttp:
    endpoint: http://jaeger:4318
    tls:
      insecure: true

processors:
  batch/traces:
    timeout: 1s
    send_batch_size: 5000

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch/traces]
      exporters: [otlphttp]
